# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ReactiveImageSearcher+RxSwift' do

  use_frameworks!

  pod 'RxSwift', '6.5.0'
  pod 'RxCocoa', '6.5.0'

  target 'ReactiveImageSearcher+RxSwiftTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'RxBlocking', '6.5.0'
    pod 'RxTest', '6.5.0'
  end

  target 'ReactiveImageSearcher+RxSwiftUITests' do
    # Pods for testing
  end

end
